package at.ac.fhcampuswien;

public enum CellState {
    ZERO_NEIGHBOURS,
    ONE_NEIGHBOUR,
    TWO_NEIGHBOURS,
    THREE_NEIGHBOURS,
    FOUR_NEIGHBOURS,
    FIVE_NEIGHBOURS,
    SIX_NEIGHBOURS,
    SEVEN_NEIGHBOURS,
    EIGTH_NEIGHBOURS,
    BOMB,
    NEW,
    FLAG,
    WRONG_FLAG
}
